#!/bin/sh

# rtorrent.rc
# system.method.set_key=event.download.finished,filebot,"execute={rtorrent-postprocess.sh,$d.get_base_path=,$d.get_name=,$d.get_custom1=}"

TORRENT_PATH="$1"
TORRENT_NAME="$2"
TORRENT_LABEL="$3"

/filebot/filebot.sh -script fn:amc --output "/downloads/Media" --action symlink --conflict skip -non-strict --log-file amc.log --def excludeList=amc.excludes unsorted=y music=y "seriesFormat=/downloads/Media/TV/{n}/Season {s.pad(2)}/{s00e00} - {t}" "animeFormat=/downloads/Media/Animes/{n}/{e.pad(3)} - {t}" "movieFormat=/downloads/Media/Movies/{n}" "musicFormat=/downloads/Media/Music/{n}/{fn}" "ut_dir=$TORRENT_PATH" "ut_kind=multi" "ut_title=$TORRENT_NAME" "ut_label=$TORRENT_LABEL" &
